### ISSUE TITLE
Placement doesn't seem to work

### ISSUE THREAD

**Issue by JoshArkMortgage** [arnnis/react-native-fast-toast#45] opened 2021-04-07 14:54 UTC
### Current behaviour
When using `{placement:'top'}` the animation of the toast changes to the top animation however the toast remains on the bottom of the page.

### Expected behaviour
Toast should be on the top of the page when placement is set to top

### Code sample
<img width="409" alt="Screen Shot 2021-04-07 at 10 52 29 AM" src="https://user-images.githubusercontent.com/69160735/113887608-a2a87a80-978f-11eb-8fb7-2149c17765cb.png">
For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |0.63.4
| react-native-fast-toast      |2.2.0
| node                         |
| npm or yarn                  |

**Comment by arnnis** [comment] 2021-04-07 16:28
This is a duplicate of #10. Check my answer

**Comment by JoshArkMortgage** [comment] 2021-04-07 18:14
Thank you so much!

**Closed** 2021-04-07 19:36 UTC
Labels: bug
